<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="121" started-at="2020-05-22T19:16:52Z" finished-at="2020-05-22T19:16:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="121" started-at="2020-05-22T19:16:52Z" finished-at="2020-05-22T19:16:52Z">
      <class name="Demo_TestNG.Demo_TestNg.TC_Login_Assertion">
        <test-method status="FAIL" signature="TC_Login_01()[pri:0, instance:Demo_TestNG.Demo_TestNg.TC_Login_Assertion@26653222]" name="TC_Login_01" duration-ms="34" started-at="2020-05-22T19:16:52Z" finished-at="2020-05-22T19:16:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Logged in as an user im expecting user here expected [user] but found [admin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Logged in as an user im expecting user here expected [user] but found [admin]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotSame(Assert.java:772)
at org.testng.Assert.assertSame(Assert.java:723)
at Demo_TestNG.Demo_TestNg.TC_Login_Assertion.TC_Login_01(TC_Login_Assertion.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_Login_01 -->
      </class> <!-- Demo_TestNG.Demo_TestNg.TC_Login_Assertion -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
